
  create table "public"."prompt_config" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "code_gen" jsonb not null default '{}'::jsonb,
    "code_audit" jsonb not null default '{}'::jsonb
      );


alter table "public"."prompt_config" enable row level security;

alter table "public"."auditor_findings" add column "dataset_hash" text;

alter table "public"."auditor_findings" add column "dataset_uri" text;

CREATE UNIQUE INDEX prompt_config_pkey ON public.prompt_config USING btree (id);

alter table "public"."prompt_config" add constraint "prompt_config_pkey" PRIMARY KEY using index "prompt_config_pkey";

grant references on table "public"."prompt_config" to "anon";

grant trigger on table "public"."prompt_config" to "anon";

grant truncate on table "public"."prompt_config" to "anon";

grant references on table "public"."prompt_config" to "authenticated";

grant trigger on table "public"."prompt_config" to "authenticated";

grant truncate on table "public"."prompt_config" to "authenticated";

grant references on table "public"."prompt_config" to "service_role";

grant trigger on table "public"."prompt_config" to "service_role";

grant truncate on table "public"."prompt_config" to "service_role";


